---
title: "Resume"
---
##Zhuo Li, MS
Email: zl2637@cumc.columbia.com 

###Education
####Columbia University 09/2017-now 
Mailman School of Public Health, New York, USA                  
Master of Science, Biostatistics, Theory and Method Track (to be expected in July 2019)

####Sichuan University                09/2013-06/2017
College of Life Science, Cheng Du, China 
Bachelor of Science, Biological Science, GPA: 3.8/4.0            

###Publication
Zhijuan Duan, Zhuo Li, Jianyuan Dai, Hongfei He, and Dan Xiao; Nucleotide base analog pyrrolo-deoxycytidine as fluorescent probe signal for enzyme-free and signal amplified nucleic acids detection; Talanta; ISSN: 0039-9140 
 
###Researches
####The standardizing of the transcriptome information analysis process           03/2017-06/2017
Responsibility: Conduct statistics analysis using R language;Sequence assembly and quality detection, differential expression analysis, GO analysis, homology sequence analysis and species composition analysis using Trinityrnaseq, BLAST, Trinotate, etc.  

####The research of nucleotide base analog pyrrolo-deoxycytidine as fluorescent probe signal for enzyme-free and signal amplified nucleic acids detection                      07/2015-12/2015
Responsibility:Tested the Thrombin using the folding feature of DNA;Detected the thrombin through UV-light imaging technology, and set up the different gradient, the concentration, reaction time and so on;Conducted data processing using origin.

###Internships
####Harbin Center for Disease Control and Prevention	  07/2016
Input data using epidemiological investigation collector software and studied its shortcomings;Analyzed, and processed data using excel and SPSS;Gained a deep understanding of public health.

####Chinese Academy of Sciences                                                    10/2016
Learning articles of a data analyze algorithm, Random Walk and did presentations of new article everyday. Learning matlab to achieve the algorithm of the article, finally tried to invent a new method and finished it in malab.
